pipeline {
    agent any

    stages {

        stage("Initial cleanup") {
            steps {
                deleteDir()
            }
        }

        stage('Checkout SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/NUELRL/php-todo'
            }
        }

        stage('Prepare Dependencies') {
            steps {
                sh '/usr/bin/php7.4 -v'

                sh 'mv .env.sample .env'

                sh '''
                sed -i 's/DB_HOST=.*/DB_HOST=172.31.36.195/' .env
                sed -i 's/DB_DATABASE=.*/DB_DATABASE=homestead/' .env
                sed -i 's/DB_USERNAME=.*/DB_USERNAME=homestead/' .env
                sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=password/' .env
                '''

                sh 'composer install'

                sh '/usr/bin/php7.4 artisan config:clear'
                sh '/usr/bin/php7.4 artisan cache:clear'
                sh 'rm -rf bootstrap/cache/*'

                sh '/usr/bin/php7.4 artisan key:generate'
                sh '/usr/bin/php7.4 artisan migrate'
                sh '/usr/bin/php7.4 artisan db:seed'
                sh '/usr/bin/php7.4 artisan config:cache'
            }
        }

        stage('Execute Unit Tests') {
            steps {
                sh './vendor/bin/phpunit'
            }
        }

        stage('Code Analysis') {
            steps {
                sh 'phploc app/ --log-csv build/logs/phploc.csv'
            }
        }

        stage('Plot Code Metrics') {
            steps {
                plot csvFileName: 'plot.csv',
                     csvSeries: [[file: 'build/logs/phploc.csv']],
                     group: 'phploc',
                     numBuilds: '100',
                     style: 'line',
                     title: 'Code Metrics',
                     yaxis: 'Values'
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'SonarQubeScanner'
            }
            steps {
                withSonarQubeEnv('sonarqube') {
                    withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                          -Dsonar.projectKey=php-todo \
                          -Dsonar.sources=app \
                          -Dsonar.host.url=http://<YOUR-SONAR-IP>:9000 \
                          -Dsonar.login=$SONAR_TOKEN
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Package Artifact') {
            steps {
                sh 'zip -qr php-todo.zip ${WORKSPACE}/*'
            }
        }

        stage('Upload Artifact to Artifactory') {
            steps {
                script { 
                    def server = Artifactory.server 'artifactory-server'                 
                    def uploadSpec = """{
                        "files": [
                          {
                           "pattern": "php-todo.zip",
                           "target": "php-todo-app-generic-local/php-todo",
                           "props": "type=zip;status=ready"
                          }
                        ]
                    }""" 

                    server.upload spec: uploadSpec
                }
            }
        }
    }
}